<?php return array (
  'Revys\\Revy\\App\\Revy' => '/storage/revy/overrides/classes/Revys/Revy/App/Revy.php',
  'Revys\\Revy\\App\\Textblock' => '/storage/revy/overrides/classes/Revys/Revy/App/Textblock.php',
  'Revys\\Revy\\App\\Page' => '/storage/revy/overrides/classes/Revys/Revy/App/Page.php',
  'Revys\\Revy\\App\\SettingsGroup' => '/storage/revy/overrides/classes/Revys/Revy/App/SettingsGroup.php',
  'Revys\\Revy\\App\\Menu' => '/storage/revy/overrides/classes/Revys/Revy/App/Menu.php',
  'Revys\\Revy\\App\\Helpers\\Tree' => '/storage/revy/overrides/classes/Revys/Revy/App/Helpers/Tree.php',
  'Revys\\Revy\\App\\Entity' => '/storage/revy/overrides/classes/Revys/Revy/App/Entity.php',
  'Revys\\Revy\\App\\Routes' => '/storage/revy/overrides/classes/Revys/Revy/App/Routes.php',
  'Revys\\Revy\\App\\Settings' => '/storage/revy/overrides/classes/Revys/Revy/App/Settings.php',
  'Revys\\Revy\\App\\Language' => '/storage/revy/overrides/classes/Revys/Revy/App/Language.php',
  'Revys\\RevyAdmin\\App\\AdminMenu' => '/storage/revy/overrides/classes/Revys/RevyAdmin/App/AdminMenu.php',
  'Revys\\RevyAdmin\\App\\Helpers\\Routes' => '/storage/revy/overrides/classes/Revys/RevyAdmin/App/Helpers/Routes.php',
  'Revys\\RevyAdmin\\App\\Translations' => '/storage/revy/overrides/classes/Revys/RevyAdmin/App/Translations.php',
  'Revys\\RevyAdmin\\App\\Alerts' => '/storage/revy/overrides/classes/Revys/RevyAdmin/App/Alerts.php',
  'Revys\\RevyAdmin\\App\\Messages' => '/storage/revy/overrides/classes/Revys/RevyAdmin/App/Messages.php',
  'Revys\\RevyAdmin\\App\\Navigation' => '/storage/revy/overrides/classes/Revys/RevyAdmin/App/Navigation.php',
  'Revys\\RevyAdmin\\App\\RevyAdmin' => '/storage/revy/overrides/classes/Revys/RevyAdmin/App/RevyAdmin.php',
  'Revys\\RevyAdmin\\App\\Http\\Controllers\\TextblockController' => '/storage/revy/overrides/classes/Revys/RevyAdmin/App/Http/Controllers/TextblockController.php',
  'Revys\\RevyAdmin\\App\\Http\\Controllers\\LanguageController' => '/storage/revy/overrides/classes/Revys/RevyAdmin/App/Http/Controllers/LanguageController.php',
  'Revys\\RevyAdmin\\App\\Http\\Controllers\\Controller' => '/storage/revy/overrides/classes/Revys/RevyAdmin/App/Http/Controllers/Controller.php',
  'Revys\\RevyAdmin\\App\\Http\\Controllers\\PageController' => '/storage/revy/overrides/classes/Revys/RevyAdmin/App/Http/Controllers/PageController.php',
  'Revys\\RevyAdmin\\App\\Http\\Controllers\\AdminMenuController' => '/storage/revy/overrides/classes/Revys/RevyAdmin/App/Http/Controllers/AdminMenuController.php',
  'Revys\\RevyAdmin\\App\\Http\\Controllers\\NavigationController' => '/storage/revy/overrides/classes/Revys/RevyAdmin/App/Http/Controllers/NavigationController.php',
  'Revys\\RevyAdmin\\App\\Http\\Controllers\\AuthController' => '/storage/revy/overrides/classes/Revys/RevyAdmin/App/Http/Controllers/AuthController.php',
  'Revys\\RevyAdmin\\App\\Http\\Controllers\\DashboardController' => '/storage/revy/overrides/classes/Revys/RevyAdmin/App/Http/Controllers/DashboardController.php',
);